<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[URl launch successfully]]>
    </line>
    <line>
      <![CDATA[capturing screenshots]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="http://localhost:8000/error.png
">View Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="http://localhost:8000/error.png
"><img src="http://localhost:8000/error.png
" height=200 width = 200></img></a>]]>
    </line>
  </reporter-output>
  <suite started-at="2023-08-15T02:28:45 IST" name="TestNG" finished-at="2023-08-15T02:28:53 IST" duration-ms="8202">
    <groups>
    </groups>
    <test started-at="2023-08-15T02:28:45 IST" name="Bank Manager Login" finished-at="2023-08-15T02:28:53 IST" duration-ms="8202">
      <class name="com.zee.testcases.BankLogin">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.zee.testcases.BankLogin@6adbc9d]" started-at="2023-08-15T02:28:45 IST" name="setup" finished-at="2023-08-15T02:28:53 IST" duration-ms="7541" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[URl launch successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:com.zee.testcases.BankLogin@6adbc9d]" started-at="2023-08-15T02:28:53 IST" name="login" finished-at="2023-08-15T02:28:53 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.zee.testcases.BankLogin@6adbc9d]" started-at="2023-08-15T02:28:53 IST" name="teardown" finished-at="2023-08-15T02:28:53 IST" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.zee.testcases.BankLogin -->
      <class name="com.zee.testcases.VerifURL">
        <test-method signature="titleURL()[pri:0, instance:com.zee.testcases.VerifURL@67c27493]" started-at="2023-08-15T02:28:53 IST" name="titleURL" finished-at="2023-08-15T02:28:53 IST" duration-ms="129" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Protractor practice website - Banking App] but found [Protractor practice website - Banking App/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Protractor practice website - Banking App] but found [Protractor practice website - Banking App/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.zee.testcases.VerifURL.titleURL(VerifURL.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[capturing screenshots]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="http://localhost:8000/error.png
">View Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="http://localhost:8000/error.png
"><img src="http://localhost:8000/error.png
" height=200 width = 200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- titleURL -->
      </class> <!-- com.zee.testcases.VerifURL -->
    </test> <!-- Bank Manager Login -->
  </suite> <!-- TestNG -->
</testng-results>
